---
title: "Group Project Visualisation"
author: "Jonathan Standing"
date: "2023-11-24"
output: pdf_document
---

```{r}
library(ggplot2)
library(dplyr)
library(ggpie)
d_israel <- read.csv("israel_practice.csv")

library(ggplot2)

# Assuming your data frame is called "df" and the column with values is called "column_name"
# Create a table of value counts
count_table <- table(d_israel$column_name)

# Create a data frame from the count table
count_d_israel <- data.frame(value = names(count_table), count = as.numeric(count_table))

# Create the pie chart
ggplot(count_d_israel, aes(x = "", y = count, fill = value)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  scale_fill_manual(values = c("1" = "green", "0" = "blue", "-1" = "red")) +
  theme_void() +
  labs(fill = "Value")
```


```{r}
if(!require(devtools)){
   install.packages("devtools")
}
devtools::install_github("rkabacoff/ggpie")

library(ggpie)

ggpie(Advanced_Sentiment)

```

```{r}
grouped_data <- d_israel %>%
  group_by(Advanced_Sentiment)

ggplot(data = grouped_data, aes(x = Advanced_Sentiment, y = count_variable)) +
  geom_bar(stat = "identity") +
  labs(title = "Grouped Bar Chart")
```

